*&---------------------------------------------------------------------*
*& Include          Z_MOD_DISCOVER2GIT_SEL
*&---------------------------------------------------------------------*

* Object type Selector
SELECTION-SCREEN SKIP.
PARAMETER: p_objtyp TYPE char10 AS LISTBOX VISIBLE LENGTH 30 USER-COMMAND v_obj .
SELECTION-SCREEN SKIP.
PARAMETERS: p_prog  LIKE trdir-name OBLIGATORY.
PARAMETERS: p_onlyz TYPE abap_bool AS CHECKBOX.
SELECTION-SCREEN SKIP.

SELECTION-SCREEN: BEGIN OF TABBED BLOCK mytab FOR 8 LINES,
TAB (20) seltab USER-COMMAND push1,
END OF BLOCK mytab.

SELECTION-SCREEN BEGIN OF SCREEN 100 AS SUBSCREEN.
  PARAMETERS: p_show  TYPE abap_bool AS CHECKBOX.
SELECTION-SCREEN END OF SCREEN 100.

SELECTION-SCREEN BEGIN OF SCREEN 200 AS SUBSCREEN.
  PARAMETERS: p_repo TYPE zabapgit-value OBLIGATORY MATCHCODE OBJECT zabapgit_repo.
  PARAMETERS: p_gitusr TYPE string DEFAULT '' LOWER CASE OBLIGATORY .
  PARAMETERS: p_gitpwd TYPE string LOWER CASE OBLIGATORY.
SELECTION-SCREEN END OF SCREEN 200.
